TingStore/Frontend/TingStore.Client/Areas/Admin/Controllers/ManagementProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;

using Microsoft.Extensions.Logging;
using TingStore.Client.Areas.Admin.Services.ProductManagement;
using TingStore.Client.Areas.Admin.Models.Products;
using System.Text.Json;
using TingStore.Client.Areas.Admin.Services.Categories;

namespace TingStore.Client.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/ManagementProduct/[action]/{id?}")]
    public class ManagementProductController : Controller
    {
        private readonly ILogger<ManagementProductController> _logger;
        private readonly IProductManagementService _productManagementService;
        private readonly ICategoryService _categoryService;

        public ManagementProductController(ILogger<ManagementProductController> logger, IProductManagementService productManagementService, ICategoryService categoryService)
        {
            _logger = logger;
            this._productManagementService = productManagementService;
            this._categoryService = categoryService;
        }

        public async Task<IActionResult> Index(int? indexpag, string? sort, string? catname)
        {
            int indexpage = indexpag ?? 1;
            _logger.LogInformation($"Page Index: {indexpage}");
            var ProductList = await _productManagementService.GetAllProducts(indexpage, sort, catname);
            System.Console.WriteLine("count: "+ProductList.Count );
            System.Console.WriteLine("pagesize: "+ProductList.PageSize );
            int numberOfPage = (int)Math.Ceiling((double)ProductList.Count / ProductList.PageSize);
            ViewBag.numberOfPage = numberOfPage;
            System.Console.WriteLine("____________________________________");
            System.Console.WriteLine("number of page: "+ numberOfPage);
            if (sort == "priceAsc")
            {
                ViewBag.sortPage = "priceAsc";
            }
            else if (sort == "priceDesc")
            {
                ViewBag.sortPage = "priceDesc";
            }
            else
            {
                ViewBag.sortPage = "default";
            }
            if(!string.IsNullOrEmpty(catname)) {
                ViewBag.vbCategory = catname;
            }
            ViewBag.CategoryList = await this._categoryService.GetAllActiveCategories();
            return View(ProductList);
        }

        public async Task<IActionResult> trash()
        {
            List<ProductResponse> productResponsesList = new List<ProductResponse>();
            var ProductList = await this._productManagementService.GetAllProductNoFilter();
            foreach(var item in ProductList) {
                if(!item.IsActive) {
                    productResponsesList.Add(item);
                }
            }
            return View(productResponsesList);
        }


        public async Task<IActionResult> ProductDetail(string id)
        {
            var product = await this._productManagementService.GetProductById(id);
            if (product == null)
            {
                return RedirectToAction("Index");
            }
            return View(product);
        }

        public IActionResult CreateProduct()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProductImage(string id, List<IFormFile> formFiles)
        {

            if (formFiles == null || formFiles.Count == 0)
            {
                ModelState.AddModelError("", "Please select at least one image.");
                return Error();
            }
            System.Console.WriteLine("__________________________");
            System.Console.WriteLine("id product: " + id);
            try
            {
                var addImageRespone = await this._productManagementService.AddProductImage(id, formFiles);
                return RedirectToAction("ProductDetail", new { id = id });
            }
            catch (System.Exception)
            {
                return RedirectToAction("ProductDetail", new { id = id });
            }
        }


        [HttpPost]
        public async Task<IActionResult> CreateProduct(ProductInput productInput)
        {
            System.Console.WriteLine(productInput.ProductFile.Count);
            ProductDescription productDescription = new ProductDescription
            {
                Brand = productInput.Brand,
                Model = productInput.Model,
                ReleaseDate = productInput.Relaease,
                Type = productInput.type,
                Size = productInput.Size,
                Resolution = productInput.Resolution,
                Dimensions = productInput.Dimensions,
                Weight = productInput.Weight,
                SIM = productInput.Sim,
                OS = productInput.Os,
                Chipset = productInput.Chipset,
                ReslaeaseDate = productInput.ReslaeaseDate,
                Description = productInput.Description
            };
            string jsonDescription = JsonSerializer.Serialize(productDescription, new JsonSerializerOptions { WriteIndented = true });
            System.Console.WriteLine("json description: " + jsonDescription);
            System.Console.WriteLine(productInput.ProductFile[0].FileName);
            ProductResquest productResquest = new ProductResquest
            {
                Name = productInput.Name,
                ProductFile = productInput.ProductFile[0],
                Description = jsonDescription.ToString(),
                Price = productInput.Price,
                Stock = productInput.Stock,
                CategoryId = productInput.Category,
                IsActive = true
            };
            System.Console.WriteLine("------------------------------------------------");
            System.Console.WriteLine(productResquest.ToString());
            try
            {
                var productRespone = await this._productManagementService.CreateProduct(productResquest);
                var addImageRespone = await this._productManagementService.AddProductImage(productRespone.Id, productInput.ProductFile);
                TempData["SuccessMessage"] = "Product created successfully!";
                return RedirectToAction("Index");
            }
            catch (System.Exception)
            {
                TempData["ErrorMessage"] = "Error creating product.";
                return View(productInput);
            }
        }

        public async Task<IActionResult> UpdateProduct(string id)
        {
            var product = await this._productManagementService.GetProductById(id);
            if (product == null)
            {
                return RedirectToAction("Index");
            }
            var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            ProductDescription productDescription = JsonSerializer.Deserialize<ProductDescription>(product.Description);
            UpdateProductInput updateProductInput = new UpdateProductInput
            {
                Id = product.Id,
                Name = product.Name,
                Brand = productDescription.Brand,
                Model = productDescription.Model,
                Relaease = productDescription.ReleaseDate,
                type = productDescription.Type,
                Size = productDescription.Size,
                Resolution = productDescription.Resolution,
                Dimensions = productDescription.Dimensions,
                Weight = productDescription.Weight,
                Sim = productDescription.SIM,
                Os = productDescription.OS,
                Chipset = productDescription.Chipset,
                ReslaeaseDate = productDescription.ReslaeaseDate,
                Description = productDescription.Description,
                Price = product.Price,
                Stock = product.Stock,
                CategoryId = product.CategoryId,
                IsActive = product.IsActive
            };
            return View(updateProductInput);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(UpdateProductInput updateProductInput)
        {
            ProductDescription productDescription = new ProductDescription
            {
                Brand = updateProductInput.Brand,
                Model = updateProductInput.Model,
                ReleaseDate = updateProductInput.Relaease,
                Type = updateProductInput.type,
                Size = updateProductInput.Size,
                Resolution = updateProductInput.Resolution,
                Dimensions = updateProductInput.Dimensions,
                Weight = updateProductInput.Weight,
                SIM = updateProductInput.Sim,
                OS = updateProductInput.Os,
                Chipset = updateProductInput.Chipset,
                ReslaeaseDate = updateProductInput.ReslaeaseDate,
                Description = updateProductInput.Description
            };
            string jsonDescription = JsonSerializer.Serialize(productDescription, new JsonSerializerOptions { WriteIndented = true });
            System.Console.WriteLine("json description: " + jsonDescription);

            UpdateProductResquest updateProductResquest = new UpdateProductResquest
            {
                Id = updateProductInput.Id,
                Name = updateProductInput.Name,
                Description = jsonDescription.ToString(),
                Price = updateProductInput.Price,
                Stock = updateProductInput.Stock,
                CategoryId = updateProductInput.CategoryId,
                IsActive = true
            };
            try
            {
                var respone = await this._productManagementService.UpdateProduct(updateProductResquest);
                TempData["SuccessMessage"] = "Product updated successfully!";

TingStore/Frontend/TingStore.Client/Areas/Admin/Views/ManagementProduct/CreateProduct.cshtml
@using TingStore.Client.Areas.Admin.Models.Products
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


@model ProductInput
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "CreateProduct";
}


<div class="row">
    <div class="col-xl-12">
        <form asp-action="CreateProduct" method="post" enctype="multipart/form-data">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Add Product Photo</h4>
                </div>
                <div class="card-body">
                    <!-- File Upload -->

                    <div class="fallback">
                        <input asp-for="ProductFile" type="file" multiple id="productImages" />
                    </div>
                    <div id="previewImages" class="d-flex flex-wrap gap-2 mt-3"></div>

                    <div class="dz-message needsclick">
                        <i class="bx bx-cloud-upload fs-48 text-primary"></i>
                        <h3 class="mt-4">Drop your images here, or <span class="text-primary">click to browse</span>
                        </h3>
                        <span class="text-muted fs-13">
                            1600 x 1200 (4:3) recommended. PNG, JPG and GIF files are allowed
                        </span>
                    </div>

                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Product Information</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label for="product-name" class="form-label">Product Name</label>
                                <input asp-for="Name" type="text" id="product-name" class="form-control"
                                    placeholder="Items Name">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <label for="Sim" class="form-label">Category</label>
                            <select asp-for="Category" class="form-control" id="Sim" data-choices data-choices-groups
                                data-placeholder="Select display">
                                <option value="">Select Sim type</option>
                                <option value="Phone">Phone</option>
                                <option value="IPad">IPad</option>
                                <option value="Tablet">Tablet</option>
                                <option value="Laptop">Laptop</option>
                                <option value="Book">Book</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="mb-3">
                                <label for="product-brand" class="form-label">Brand</label>
                                <input asp-for="Brand" type="text" id="product-brand" class="form-control"
                                    placeholder="Brand Name">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="mb-3">
                                <label for="product-weight" class="form-label">Weight</label>
                                <input asp-for="Weight" type="text" id="product-weight" class="form-control"
                                    placeholder="In gm & kg">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <label for="display" class="form-label">Display type</label>
                            <select asp-for="type" class="form-control" id="display" data-choices data-choices-groups
                                data-placeholder="Select display">
                                <option value="">Select display type</option>
                                <option value="Amoled">Amoled</option>
                                <option value="LCD">LCD</option>
                                <option value="IPS">IPS</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="mb-3">
                                <label for="product-brand" class="form-label">Model</label>
                                <input asp-for="Model" type="text" id="product-brand" class="form-control"
                                    placeholder="Model Name">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="mb-3">
                                <label for="product-weight" class="form-label">Size</label>
                                <input asp-for="Size" type="text" id="product-weight" class="form-control"
                                    placeholder="px">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="mb-3">
                                <label for="product-weight" class="form-label">Relaease</label>
                                <input asp-for="Relaease" type="date" id="product-weight" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="mb-3">
                                <label for="product-brand" class="form-label">Resolution</label>
                                <input asp-for="Resolution" type="text" id="product-brand" class="form-control"
                                    placeholder="Resolution">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="mb-3">
                                <label for="product-weight" class="form-label">Dimensions</label>
                                <input asp-for="Dimensions" type="text" id="product-weight" class="form-control"
                                    placeholder="Dimensions">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <label for="Sim" class="form-label">SIM</label>
                            <select asp-for="Sim" class="form-control" id="Sim" data-choices data-choices-groups
                                data-placeholder="Select display">
                                <option value="">Select Sim type</option>
                                <option value="Dual sim">Dual sim</option>
                                <option value="Single sim">Single sim</option>
                                <option value="E-sim">E-sim</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <label for="os" class="form-label">OS</label>
                            <select asp-for="Os" class="form-control" id="os" data-choices data-choices-groups
                                data-placeholder="Select display">
                                <option value="">Select Sim type</option>
                                <option value="Amoled">IOS</option>
                                <option value="Android">Android</option>
                            </select>
                        </div>
                        <div class="col-lg-4">
                            <div class="mb-3">
                                <label for="product-weight" class="form-label">Chip set</label>
                                <input asp-for="Chipset" type="text" id="product-weight" class="form-control"
                                    placeholder="Chipset">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="mb-3">
                                <label for="product-weight" class="form-label">Reslaease Date</label>
                                <input asp-for="ReslaeaseDate" type="date" id="product-weight" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="mb-3">
                                <label for="description" class="form-label">Description</label>
                                <textarea asp-for="Description" class="form-control bg-light-subtle" id="description"
                                    rows="7" placeholder="Short description about the product"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Pricing Details</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <label for="product-price" class="form-label">Price</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text fs-20"><i class='bx bx-dollar'></i></span>
                                <input asp-for="Price" type="number" id="product-price" class="form-control"
                                    placeholder="000">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <label for="product-discount" class="form-label">Discount</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text fs-20"><i class='bx bxs-discount'></i></span>
                                <input asp-for="Stock" type="number" id="product-discount" class="form-control"
                                    placeholder="000">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="p-3 bg-light mb-3 rounded">
                <div class="row justify-content-end g-2">
                    <div class="col-lg-2">
                        <input class="btn btn-outline-secondary w-100" type="submit" value="Create Product">
                    </div>
                    <div class="col-lg-2">
                        <a class="btn btn-primary w-100" style="cursor: pointer;"
                            href="@Url.Action("Index", new { indexpag = 1 })">Cancel</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    document.getElementById('productImages').addEventListener('change', function (event) {
        const previewContainer = document.getElementById('previewImages');
        previewContainer.innerHTML = ""; // Xóa ảnh cũ khi chọn ảnh mới

        const files = event.target.files;
        if (files.length > 4) {
            alert("Bạn chỉ có thể chọn tối đa 4 ảnh.");
            return;
        }

        for (let i = 0; i < files.length; i++) {
            const file = files[i];
            const reader = new FileReader();

            reader.onload = function (e) {
                const img = document.createElement('img');
                img.src = e.target.result;
                img.classList.add('img-fluid', 'rounded', 'border', 'p-1');
                img.style.width = "100px"; // Điều chỉnh kích thước ảnh
                img.style.height = "100px";

                previewContainer.appendChild(img);
            };

            reader.readAsDataURL(file);
        }
    });
</script>

TingStore/Frontend/TingStore.Client/Areas/Admin/Views/ManagementProduct/Index.cshtml
@using TingStore.Client.Areas.Admin.Models.Products
@using TingStore.Client.Areas.Admin.Models.Products.Specs
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


@model Pagination<ProductResponse>
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Index";
}

@{
    string sortPage = @ViewBag.sortPage;
    string vbCategory = @ViewBag.vbCategory;
    string categoryText = string.IsNullOrEmpty(vbCategory) ? "Default" : vbCategory;
}
<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center gap-1">
                <h4 class="card-title flex-grow-1">All Product List</h4>
                <a asp-area="Admin" asp-controller="ManagementProduct" asp-action="trash"
                    class="btn btn-sm btn-primary">Trash</a>
                <a asp-area="Admin" asp-controller="ManagementProduct" asp-action="CreateProduct"
                    class="btn btn-sm btn-primary">Add Product</a>
                <h5 style="margin-top: 10px; padding-left: 10px;">Category:</h5>
                <div class="dropdown">
                    <a href="#" class="dropdown-toggle btn btn-sm btn-outline-light" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        @categoryText
                    </a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <!-- item-->
                        <a class="dropdown-item" href="@Url.Action("Index", new { indexpag = 1 })">Default</a>
                        @foreach(var item in ViewBag.CategoryList) {
                            <a class="dropdown-item" href="@Url.Action("Index", new { catname = @item.Name })">@item.Name</a>
                        }
                    </div>
                </div>
                <h5 style="margin-top: 10px; padding-left: 10px;">Sort:</h5>
                <div class="dropdown">
                    <a href="#" class="dropdown-toggle btn btn-sm btn-outline-light" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        @sortPage
                    </a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <!-- item-->
                        <a class="dropdown-item" href="@Url.Action("Index", new { indexpag = 1 })">Default</a>
                        <a class="dropdown-item" href="@Url.Action("Index", new { sort = "priceDesc" , catname = vbCategory})">Price
                            decrease</a>
                        <a class="dropdown-item" href="@Url.Action("Index", new { sort = "priceAsc" , catname = vbCategory})">Price
                            increase</a>
                    </div>
                </div>
            </div>
            <div>
                <div class="table-responsive">
                    <table class="table align-middle mb-0 table-hover table-centered">
                        <thead class="bg-light-subtle">
                            <tr>
                                <th style="width: 20px;">
                                    <div class="form-check ms-1">
                                        <input type="checkbox" class="form-check-input" id="customCheck1">
                                        <label class="form-check-label" for="customCheck1"></label>
                                    </div>
                                </th>
                                <th>Product Name & Size</th>
                                <th>Price</th>
                                <th>Stock</th>
                                <th>Category</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Data)
                            {
                                <tr>
                                    <td>
                                        <div class="form-check ms-1">
                                            <input type="checkbox" class="form-check-input" id="customCheck2">
                                            <label class="form-check-label" for="customCheck2">&nbsp;</label>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center gap-2">
                                            <div
                                                class="rounded bg-light avatar-md d-flex align-items-center justify-content-center">
                                                <img src="@item.ProductImage" alt="" class="avatar-md">
                                            </div>
                                            <div>
                                                <a asp-action="ProductDetail" asp-route-id="@item.Id" class="text-dark fw-medium fs-15">@item.Name</a>
                                                @if (!item.IsActive)
                                                {
                                                    <p class="text-danger mb-0 mt-1 fs-13">Has been deleted</p>
                                                }
                                            </div>
                                        </div>
                                    </td>
                                    <td>@string.Format(new System.Globalization.CultureInfo("vi-VN"), "{0:N0}", item.Price)đ
                                    </td>
                                    <td>
                                        <p class="mb-1 text-muted"><span class="text-dark fw-medium">@item.Stock Item</span>
                                            Left</p>
                                    </td>
                                    <td> @item.CategoryId</td>
                                    <td>
                                        <div class="d-flex gap-2">
                                            <a asp-action="ProductDetail" asp-route-id="@item.Id" class="btn btn-light btn-sm"><iconify-icon icon="solar:eye-broken" class="align-middle fs-18"></iconify-icon></a>
                                            <a asp-action="UpdateProduct" asp-route-id="@item.Id" class="btn btn-soft-primary btn-sm"><iconify-icon
                                                    icon="solar:pen-2-broken" class="align-middle fs-18"></iconify-icon></a>
                                            <a asp-action="DeleteProduct" asp-route-id="@item.Id" class="btn btn-soft-danger btn-sm"><iconify-icon
                                                    icon="solar:trash-bin-minimalistic-2-broken"
                                                    class="align-middle fs-18"></iconify-icon></a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- end table-responsive -->
            </div>
            <div class="card-footer border-top">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-end mb-0">
                        <li class="page-item"><a class="page-link" href="javascript:void(0);">Previous</a></li>
                        @for (int i = 1; i <= ViewBag.NumberOfPage; i++)
                        {
                            <li class="page-item @(Model.PageIndex == i ? "active" : "")">
                                <a class="page-link"
                                    href="@Url.Action("Index", new { indexpag = i, sort = sortPage , catname = vbCategory})">@i</a>
                            </li>
                        }
                        <li class="page-item"><a class="page-link" href="javascript:void(0);">Next</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
        @if (TempData["SuccessMessage"] != null)
        {
            @:Swal.fire({
            @:    icon: 'success',
            @:    title: 'Success!',
            @:    text: '@TempData["SuccessMessage"]',
            @:    confirmButtonText: 'OK'
            @:});
        }
        @if (TempData["ErrorMessage"] != null)
        {
            @:Swal.fire({
            @:icon: 'error',
            @:title: 'Oops...',
            @:text: '@TempData["ErrorMessage"]',
            @:confirmButtonText: 'OK'
            @:});
        }
        });
    </script>
}